// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/Control.proto

package zensayyy.fm.proto;

public final class Control {
  private Control() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StreamTOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zensayyy.fm.proto.StreamT)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string videoId = 1;</code>
     * @return The videoId.
     */
    java.lang.String getVideoId();
    /**
     * <code>string videoId = 1;</code>
     * @return The bytes for videoId.
     */
    com.google.protobuf.ByteString
        getVideoIdBytes();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>.zensayyy.fm.proto.StreamAction action = 4;</code>
     * @return The enum numeric value on the wire for action.
     */
    int getActionValue();
    /**
     * <code>.zensayyy.fm.proto.StreamAction action = 4;</code>
     * @return The action.
     */
    zensayyy.fm.proto.Stream.StreamAction getAction();
  }
  /**
   * Protobuf type {@code zensayyy.fm.proto.StreamT}
   */
  public static final class StreamT extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zensayyy.fm.proto.StreamT)
      StreamTOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StreamT.newBuilder() to construct.
    private StreamT(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StreamT() {
      videoId_ = "";
      title_ = "";
      description_ = "";
      action_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StreamT();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zensayyy.fm.proto.Control.internal_static_zensayyy_fm_proto_StreamT_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zensayyy.fm.proto.Control.internal_static_zensayyy_fm_proto_StreamT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zensayyy.fm.proto.Control.StreamT.class, zensayyy.fm.proto.Control.StreamT.Builder.class);
    }

    public static final int VIDEOID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object videoId_ = "";
    /**
     * <code>string videoId = 1;</code>
     * @return The videoId.
     */
    @java.lang.Override
    public java.lang.String getVideoId() {
      java.lang.Object ref = videoId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        videoId_ = s;
        return s;
      }
    }
    /**
     * <code>string videoId = 1;</code>
     * @return The bytes for videoId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVideoIdBytes() {
      java.lang.Object ref = videoId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        videoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 4;
    private int action_ = 0;
    /**
     * <code>.zensayyy.fm.proto.StreamAction action = 4;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override public int getActionValue() {
      return action_;
    }
    /**
     * <code>.zensayyy.fm.proto.StreamAction action = 4;</code>
     * @return The action.
     */
    @java.lang.Override public zensayyy.fm.proto.Stream.StreamAction getAction() {
      zensayyy.fm.proto.Stream.StreamAction result = zensayyy.fm.proto.Stream.StreamAction.forNumber(action_);
      return result == null ? zensayyy.fm.proto.Stream.StreamAction.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(videoId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, videoId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      if (action_ != zensayyy.fm.proto.Stream.StreamAction.ADD.getNumber()) {
        output.writeEnum(4, action_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(videoId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, videoId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      if (action_ != zensayyy.fm.proto.Stream.StreamAction.ADD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, action_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zensayyy.fm.proto.Control.StreamT)) {
        return super.equals(obj);
      }
      zensayyy.fm.proto.Control.StreamT other = (zensayyy.fm.proto.Control.StreamT) obj;

      if (!getVideoId()
          .equals(other.getVideoId())) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (action_ != other.action_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VIDEOID_FIELD_NUMBER;
      hash = (53 * hash) + getVideoId().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + action_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zensayyy.fm.proto.Control.StreamT parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Control.StreamT parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Control.StreamT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Control.StreamT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Control.StreamT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Control.StreamT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Control.StreamT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Control.StreamT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Control.StreamT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Control.StreamT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Control.StreamT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Control.StreamT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zensayyy.fm.proto.Control.StreamT prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zensayyy.fm.proto.StreamT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zensayyy.fm.proto.StreamT)
        zensayyy.fm.proto.Control.StreamTOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zensayyy.fm.proto.Control.internal_static_zensayyy_fm_proto_StreamT_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zensayyy.fm.proto.Control.internal_static_zensayyy_fm_proto_StreamT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zensayyy.fm.proto.Control.StreamT.class, zensayyy.fm.proto.Control.StreamT.Builder.class);
      }

      // Construct using zensayyy.fm.proto.Control.StreamT.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        videoId_ = "";
        title_ = "";
        description_ = "";
        action_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zensayyy.fm.proto.Control.internal_static_zensayyy_fm_proto_StreamT_descriptor;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Control.StreamT getDefaultInstanceForType() {
        return zensayyy.fm.proto.Control.StreamT.getDefaultInstance();
      }

      @java.lang.Override
      public zensayyy.fm.proto.Control.StreamT build() {
        zensayyy.fm.proto.Control.StreamT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Control.StreamT buildPartial() {
        zensayyy.fm.proto.Control.StreamT result = new zensayyy.fm.proto.Control.StreamT(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(zensayyy.fm.proto.Control.StreamT result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.videoId_ = videoId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.title_ = title_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.description_ = description_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.action_ = action_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zensayyy.fm.proto.Control.StreamT) {
          return mergeFrom((zensayyy.fm.proto.Control.StreamT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zensayyy.fm.proto.Control.StreamT other) {
        if (other == zensayyy.fm.proto.Control.StreamT.getDefaultInstance()) return this;
        if (!other.getVideoId().isEmpty()) {
          videoId_ = other.videoId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.action_ != 0) {
          setActionValue(other.getActionValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                videoId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                title_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                action_ = input.readEnum();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object videoId_ = "";
      /**
       * <code>string videoId = 1;</code>
       * @return The videoId.
       */
      public java.lang.String getVideoId() {
        java.lang.Object ref = videoId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          videoId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string videoId = 1;</code>
       * @return The bytes for videoId.
       */
      public com.google.protobuf.ByteString
          getVideoIdBytes() {
        java.lang.Object ref = videoId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          videoId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string videoId = 1;</code>
       * @param value The videoId to set.
       * @return This builder for chaining.
       */
      public Builder setVideoId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        videoId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string videoId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVideoId() {
        videoId_ = getDefaultInstance().getVideoId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string videoId = 1;</code>
       * @param value The bytes for videoId to set.
       * @return This builder for chaining.
       */
      public Builder setVideoIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        videoId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int action_ = 0;
      /**
       * <code>.zensayyy.fm.proto.StreamAction action = 4;</code>
       * @return The enum numeric value on the wire for action.
       */
      @java.lang.Override public int getActionValue() {
        return action_;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamAction action = 4;</code>
       * @param value The enum numeric value on the wire for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionValue(int value) {
        action_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamAction action = 4;</code>
       * @return The action.
       */
      @java.lang.Override
      public zensayyy.fm.proto.Stream.StreamAction getAction() {
        zensayyy.fm.proto.Stream.StreamAction result = zensayyy.fm.proto.Stream.StreamAction.forNumber(action_);
        return result == null ? zensayyy.fm.proto.Stream.StreamAction.UNRECOGNIZED : result;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamAction action = 4;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(zensayyy.fm.proto.Stream.StreamAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamAction action = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000008);
        action_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zensayyy.fm.proto.StreamT)
    }

    // @@protoc_insertion_point(class_scope:zensayyy.fm.proto.StreamT)
    private static final zensayyy.fm.proto.Control.StreamT DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zensayyy.fm.proto.Control.StreamT();
    }

    public static zensayyy.fm.proto.Control.StreamT getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StreamT>
        PARSER = new com.google.protobuf.AbstractParser<StreamT>() {
      @java.lang.Override
      public StreamT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StreamT> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StreamT> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public zensayyy.fm.proto.Control.StreamT getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ControlMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zensayyy.fm.proto.ControlMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
     * @return The id.
     */
    zensayyy.fm.proto.Stream.StreamJoin getId();
    /**
     * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
     */
    zensayyy.fm.proto.Stream.StreamJoinOrBuilder getIdOrBuilder();

    /**
     * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
     * @return Whether the stream field is set.
     */
    boolean hasStream();
    /**
     * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
     * @return The stream.
     */
    zensayyy.fm.proto.Control.StreamT getStream();
    /**
     * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
     */
    zensayyy.fm.proto.Control.StreamTOrBuilder getStreamOrBuilder();

    zensayyy.fm.proto.Control.ControlMessage.MessageCase getMessageCase();
  }
  /**
   * Protobuf type {@code zensayyy.fm.proto.ControlMessage}
   */
  public static final class ControlMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zensayyy.fm.proto.ControlMessage)
      ControlMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ControlMessage.newBuilder() to construct.
    private ControlMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ControlMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ControlMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zensayyy.fm.proto.Control.internal_static_zensayyy_fm_proto_ControlMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zensayyy.fm.proto.Control.internal_static_zensayyy_fm_proto_ControlMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zensayyy.fm.proto.Control.ControlMessage.class, zensayyy.fm.proto.Control.ControlMessage.Builder.class);
    }

    private int messageCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object message_;
    public enum MessageCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      STREAM(2),
      MESSAGE_NOT_SET(0);
      private final int value;
      private MessageCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageCase valueOf(int value) {
        return forNumber(value);
      }

      public static MessageCase forNumber(int value) {
        switch (value) {
          case 2: return STREAM;
          case 0: return MESSAGE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageCase
    getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private zensayyy.fm.proto.Stream.StreamJoin id_;
    /**
     * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return id_ != null;
    }
    /**
     * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public zensayyy.fm.proto.Stream.StreamJoin getId() {
      return id_ == null ? zensayyy.fm.proto.Stream.StreamJoin.getDefaultInstance() : id_;
    }
    /**
     * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
     */
    @java.lang.Override
    public zensayyy.fm.proto.Stream.StreamJoinOrBuilder getIdOrBuilder() {
      return id_ == null ? zensayyy.fm.proto.Stream.StreamJoin.getDefaultInstance() : id_;
    }

    public static final int STREAM_FIELD_NUMBER = 2;
    /**
     * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
     * @return Whether the stream field is set.
     */
    @java.lang.Override
    public boolean hasStream() {
      return messageCase_ == 2;
    }
    /**
     * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
     * @return The stream.
     */
    @java.lang.Override
    public zensayyy.fm.proto.Control.StreamT getStream() {
      if (messageCase_ == 2) {
         return (zensayyy.fm.proto.Control.StreamT) message_;
      }
      return zensayyy.fm.proto.Control.StreamT.getDefaultInstance();
    }
    /**
     * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
     */
    @java.lang.Override
    public zensayyy.fm.proto.Control.StreamTOrBuilder getStreamOrBuilder() {
      if (messageCase_ == 2) {
         return (zensayyy.fm.proto.Control.StreamT) message_;
      }
      return zensayyy.fm.proto.Control.StreamT.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != null) {
        output.writeMessage(1, getId());
      }
      if (messageCase_ == 2) {
        output.writeMessage(2, (zensayyy.fm.proto.Control.StreamT) message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getId());
      }
      if (messageCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (zensayyy.fm.proto.Control.StreamT) message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zensayyy.fm.proto.Control.ControlMessage)) {
        return super.equals(obj);
      }
      zensayyy.fm.proto.Control.ControlMessage other = (zensayyy.fm.proto.Control.ControlMessage) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (!getMessageCase().equals(other.getMessageCase())) return false;
      switch (messageCase_) {
        case 2:
          if (!getStream()
              .equals(other.getStream())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      switch (messageCase_) {
        case 2:
          hash = (37 * hash) + STREAM_FIELD_NUMBER;
          hash = (53 * hash) + getStream().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zensayyy.fm.proto.Control.ControlMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Control.ControlMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Control.ControlMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Control.ControlMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Control.ControlMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Control.ControlMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Control.ControlMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Control.ControlMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Control.ControlMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Control.ControlMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Control.ControlMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Control.ControlMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zensayyy.fm.proto.Control.ControlMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zensayyy.fm.proto.ControlMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zensayyy.fm.proto.ControlMessage)
        zensayyy.fm.proto.Control.ControlMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zensayyy.fm.proto.Control.internal_static_zensayyy_fm_proto_ControlMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zensayyy.fm.proto.Control.internal_static_zensayyy_fm_proto_ControlMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zensayyy.fm.proto.Control.ControlMessage.class, zensayyy.fm.proto.Control.ControlMessage.Builder.class);
      }

      // Construct using zensayyy.fm.proto.Control.ControlMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = null;
        if (idBuilder_ != null) {
          idBuilder_.dispose();
          idBuilder_ = null;
        }
        if (streamBuilder_ != null) {
          streamBuilder_.clear();
        }
        messageCase_ = 0;
        message_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zensayyy.fm.proto.Control.internal_static_zensayyy_fm_proto_ControlMessage_descriptor;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Control.ControlMessage getDefaultInstanceForType() {
        return zensayyy.fm.proto.Control.ControlMessage.getDefaultInstance();
      }

      @java.lang.Override
      public zensayyy.fm.proto.Control.ControlMessage build() {
        zensayyy.fm.proto.Control.ControlMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Control.ControlMessage buildPartial() {
        zensayyy.fm.proto.Control.ControlMessage result = new zensayyy.fm.proto.Control.ControlMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(zensayyy.fm.proto.Control.ControlMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = idBuilder_ == null
              ? id_
              : idBuilder_.build();
        }
      }

      private void buildPartialOneofs(zensayyy.fm.proto.Control.ControlMessage result) {
        result.messageCase_ = messageCase_;
        result.message_ = this.message_;
        if (messageCase_ == 2 &&
            streamBuilder_ != null) {
          result.message_ = streamBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zensayyy.fm.proto.Control.ControlMessage) {
          return mergeFrom((zensayyy.fm.proto.Control.ControlMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zensayyy.fm.proto.Control.ControlMessage other) {
        if (other == zensayyy.fm.proto.Control.ControlMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        switch (other.getMessageCase()) {
          case STREAM: {
            mergeStream(other.getStream());
            break;
          }
          case MESSAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getIdFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getStreamFieldBuilder().getBuilder(),
                    extensionRegistry);
                messageCase_ = 2;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int messageCase_ = 0;
      private java.lang.Object message_;
      public MessageCase
          getMessageCase() {
        return MessageCase.forNumber(
            messageCase_);
      }

      public Builder clearMessage() {
        messageCase_ = 0;
        message_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private zensayyy.fm.proto.Stream.StreamJoin id_;
      private com.google.protobuf.SingleFieldBuilderV3<
          zensayyy.fm.proto.Stream.StreamJoin, zensayyy.fm.proto.Stream.StreamJoin.Builder, zensayyy.fm.proto.Stream.StreamJoinOrBuilder> idBuilder_;
      /**
       * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
       * @return The id.
       */
      public zensayyy.fm.proto.Stream.StreamJoin getId() {
        if (idBuilder_ == null) {
          return id_ == null ? zensayyy.fm.proto.Stream.StreamJoin.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
       */
      public Builder setId(zensayyy.fm.proto.Stream.StreamJoin value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
        } else {
          idBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
       */
      public Builder setId(
          zensayyy.fm.proto.Stream.StreamJoin.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
       */
      public Builder mergeId(zensayyy.fm.proto.Stream.StreamJoin value) {
        if (idBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            id_ != null &&
            id_ != zensayyy.fm.proto.Stream.StreamJoin.getDefaultInstance()) {
            getIdBuilder().mergeFrom(value);
          } else {
            id_ = value;
          }
        } else {
          idBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = null;
        if (idBuilder_ != null) {
          idBuilder_.dispose();
          idBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
       */
      public zensayyy.fm.proto.Stream.StreamJoin.Builder getIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
       */
      public zensayyy.fm.proto.Stream.StreamJoinOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              zensayyy.fm.proto.Stream.StreamJoin.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>.zensayyy.fm.proto.StreamJoin id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          zensayyy.fm.proto.Stream.StreamJoin, zensayyy.fm.proto.Stream.StreamJoin.Builder, zensayyy.fm.proto.Stream.StreamJoinOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              zensayyy.fm.proto.Stream.StreamJoin, zensayyy.fm.proto.Stream.StreamJoin.Builder, zensayyy.fm.proto.Stream.StreamJoinOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          zensayyy.fm.proto.Control.StreamT, zensayyy.fm.proto.Control.StreamT.Builder, zensayyy.fm.proto.Control.StreamTOrBuilder> streamBuilder_;
      /**
       * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
       * @return Whether the stream field is set.
       */
      @java.lang.Override
      public boolean hasStream() {
        return messageCase_ == 2;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
       * @return The stream.
       */
      @java.lang.Override
      public zensayyy.fm.proto.Control.StreamT getStream() {
        if (streamBuilder_ == null) {
          if (messageCase_ == 2) {
            return (zensayyy.fm.proto.Control.StreamT) message_;
          }
          return zensayyy.fm.proto.Control.StreamT.getDefaultInstance();
        } else {
          if (messageCase_ == 2) {
            return streamBuilder_.getMessage();
          }
          return zensayyy.fm.proto.Control.StreamT.getDefaultInstance();
        }
      }
      /**
       * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
       */
      public Builder setStream(zensayyy.fm.proto.Control.StreamT value) {
        if (streamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          streamBuilder_.setMessage(value);
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
       */
      public Builder setStream(
          zensayyy.fm.proto.Control.StreamT.Builder builderForValue) {
        if (streamBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          streamBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
       */
      public Builder mergeStream(zensayyy.fm.proto.Control.StreamT value) {
        if (streamBuilder_ == null) {
          if (messageCase_ == 2 &&
              message_ != zensayyy.fm.proto.Control.StreamT.getDefaultInstance()) {
            message_ = zensayyy.fm.proto.Control.StreamT.newBuilder((zensayyy.fm.proto.Control.StreamT) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 2) {
            streamBuilder_.mergeFrom(value);
          } else {
            streamBuilder_.setMessage(value);
          }
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
       */
      public Builder clearStream() {
        if (streamBuilder_ == null) {
          if (messageCase_ == 2) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 2) {
            messageCase_ = 0;
            message_ = null;
          }
          streamBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
       */
      public zensayyy.fm.proto.Control.StreamT.Builder getStreamBuilder() {
        return getStreamFieldBuilder().getBuilder();
      }
      /**
       * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
       */
      @java.lang.Override
      public zensayyy.fm.proto.Control.StreamTOrBuilder getStreamOrBuilder() {
        if ((messageCase_ == 2) && (streamBuilder_ != null)) {
          return streamBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 2) {
            return (zensayyy.fm.proto.Control.StreamT) message_;
          }
          return zensayyy.fm.proto.Control.StreamT.getDefaultInstance();
        }
      }
      /**
       * <code>.zensayyy.fm.proto.StreamT stream = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          zensayyy.fm.proto.Control.StreamT, zensayyy.fm.proto.Control.StreamT.Builder, zensayyy.fm.proto.Control.StreamTOrBuilder> 
          getStreamFieldBuilder() {
        if (streamBuilder_ == null) {
          if (!(messageCase_ == 2)) {
            message_ = zensayyy.fm.proto.Control.StreamT.getDefaultInstance();
          }
          streamBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              zensayyy.fm.proto.Control.StreamT, zensayyy.fm.proto.Control.StreamT.Builder, zensayyy.fm.proto.Control.StreamTOrBuilder>(
                  (zensayyy.fm.proto.Control.StreamT) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 2;
        onChanged();
        return streamBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zensayyy.fm.proto.ControlMessage)
    }

    // @@protoc_insertion_point(class_scope:zensayyy.fm.proto.ControlMessage)
    private static final zensayyy.fm.proto.Control.ControlMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zensayyy.fm.proto.Control.ControlMessage();
    }

    public static zensayyy.fm.proto.Control.ControlMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ControlMessage>
        PARSER = new com.google.protobuf.AbstractParser<ControlMessage>() {
      @java.lang.Override
      public ControlMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ControlMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ControlMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public zensayyy.fm.proto.Control.ControlMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zensayyy_fm_proto_StreamT_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zensayyy_fm_proto_StreamT_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zensayyy_fm_proto_ControlMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zensayyy_fm_proto_ControlMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026protocol/Control.proto\022\021zensayyy.fm.pr" +
      "oto\032\025protocol/Stream.proto\"o\n\007StreamT\022\017\n" +
      "\007videoId\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\023\n\013descrip" +
      "tion\030\003 \001(\t\022/\n\006action\030\004 \001(\0162\037.zensayyy.fm" +
      ".proto.StreamAction\"t\n\016ControlMessage\022)\n" +
      "\002id\030\001 \001(\0132\035.zensayyy.fm.proto.StreamJoin" +
      "\022,\n\006stream\030\002 \001(\0132\032.zensayyy.fm.proto.Str" +
      "eamTH\000B\t\n\007messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          zensayyy.fm.proto.Stream.getDescriptor(),
        });
    internal_static_zensayyy_fm_proto_StreamT_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zensayyy_fm_proto_StreamT_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zensayyy_fm_proto_StreamT_descriptor,
        new java.lang.String[] { "VideoId", "Title", "Description", "Action", });
    internal_static_zensayyy_fm_proto_ControlMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zensayyy_fm_proto_ControlMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zensayyy_fm_proto_ControlMessage_descriptor,
        new java.lang.String[] { "Id", "Stream", "Message", });
    zensayyy.fm.proto.Stream.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
