// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/Fm.proto

package zensayyy.fm.proto;

public final class Fm {
  private Fm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FmControlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zensayyy.fm.proto.FmControl)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.zensayyy.fm.proto.FmControl.Control control = 1;</code>
     * @return The enum numeric value on the wire for control.
     */
    int getControlValue();
    /**
     * <code>.zensayyy.fm.proto.FmControl.Control control = 1;</code>
     * @return The control.
     */
    zensayyy.fm.proto.Fm.FmControl.Control getControl();

    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
     */
    java.util.List<zensayyy.fm.proto.TrackOuterClass.Track> 
        getTracksList();
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
     */
    zensayyy.fm.proto.TrackOuterClass.Track getTracks(int index);
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
     */
    int getTracksCount();
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
     */
    java.util.List<? extends zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder> 
        getTracksOrBuilderList();
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
     */
    zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder getTracksOrBuilder(
        int index);
  }
  /**
   * <pre>
   *&#47; Control Messages received by the Client
   * / Todo: Control Messages for Synchronize Streams
   * </pre>
   *
   * Protobuf type {@code zensayyy.fm.proto.FmControl}
   */
  public static final class FmControl extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zensayyy.fm.proto.FmControl)
      FmControlOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FmControl.newBuilder() to construct.
    private FmControl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FmControl() {
      control_ = 0;
      tracks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FmControl();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmControl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zensayyy.fm.proto.Fm.FmControl.class, zensayyy.fm.proto.Fm.FmControl.Builder.class);
    }

    /**
     * Protobuf enum {@code zensayyy.fm.proto.FmControl.Control}
     */
    public enum Control
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * client request DATA
       * </pre>
       *
       * <code>SYNC_REQ = 0;</code>
       */
      SYNC_REQ(0),
      /**
       * <code>DATA = 1;</code>
       */
      DATA(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * client request DATA
       * </pre>
       *
       * <code>SYNC_REQ = 0;</code>
       */
      public static final int SYNC_REQ_VALUE = 0;
      /**
       * <code>DATA = 1;</code>
       */
      public static final int DATA_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Control valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Control forNumber(int value) {
        switch (value) {
          case 0: return SYNC_REQ;
          case 1: return DATA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Control>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Control> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Control>() {
              public Control findValueByNumber(int number) {
                return Control.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return zensayyy.fm.proto.Fm.FmControl.getDescriptor().getEnumTypes().get(0);
      }

      private static final Control[] VALUES = values();

      public static Control valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Control(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:zensayyy.fm.proto.FmControl.Control)
    }

    public static final int CONTROL_FIELD_NUMBER = 1;
    private int control_ = 0;
    /**
     * <code>.zensayyy.fm.proto.FmControl.Control control = 1;</code>
     * @return The enum numeric value on the wire for control.
     */
    @java.lang.Override public int getControlValue() {
      return control_;
    }
    /**
     * <code>.zensayyy.fm.proto.FmControl.Control control = 1;</code>
     * @return The control.
     */
    @java.lang.Override public zensayyy.fm.proto.Fm.FmControl.Control getControl() {
      zensayyy.fm.proto.Fm.FmControl.Control result = zensayyy.fm.proto.Fm.FmControl.Control.forNumber(control_);
      return result == null ? zensayyy.fm.proto.Fm.FmControl.Control.UNRECOGNIZED : result;
    }

    public static final int TRACKS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<zensayyy.fm.proto.TrackOuterClass.Track> tracks_;
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
     */
    @java.lang.Override
    public java.util.List<zensayyy.fm.proto.TrackOuterClass.Track> getTracksList() {
      return tracks_;
    }
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder> 
        getTracksOrBuilderList() {
      return tracks_;
    }
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
     */
    @java.lang.Override
    public int getTracksCount() {
      return tracks_.size();
    }
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
     */
    @java.lang.Override
    public zensayyy.fm.proto.TrackOuterClass.Track getTracks(int index) {
      return tracks_.get(index);
    }
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
     */
    @java.lang.Override
    public zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder getTracksOrBuilder(
        int index) {
      return tracks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (control_ != zensayyy.fm.proto.Fm.FmControl.Control.SYNC_REQ.getNumber()) {
        output.writeEnum(1, control_);
      }
      for (int i = 0; i < tracks_.size(); i++) {
        output.writeMessage(2, tracks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (control_ != zensayyy.fm.proto.Fm.FmControl.Control.SYNC_REQ.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, control_);
      }
      for (int i = 0; i < tracks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, tracks_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zensayyy.fm.proto.Fm.FmControl)) {
        return super.equals(obj);
      }
      zensayyy.fm.proto.Fm.FmControl other = (zensayyy.fm.proto.Fm.FmControl) obj;

      if (control_ != other.control_) return false;
      if (!getTracksList()
          .equals(other.getTracksList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTROL_FIELD_NUMBER;
      hash = (53 * hash) + control_;
      if (getTracksCount() > 0) {
        hash = (37 * hash) + TRACKS_FIELD_NUMBER;
        hash = (53 * hash) + getTracksList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zensayyy.fm.proto.Fm.FmControl parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Fm.FmControl parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmControl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Fm.FmControl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmControl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Fm.FmControl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmControl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Fm.FmControl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmControl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Fm.FmControl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmControl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Fm.FmControl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zensayyy.fm.proto.Fm.FmControl prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *&#47; Control Messages received by the Client
     * / Todo: Control Messages for Synchronize Streams
     * </pre>
     *
     * Protobuf type {@code zensayyy.fm.proto.FmControl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zensayyy.fm.proto.FmControl)
        zensayyy.fm.proto.Fm.FmControlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmControl_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmControl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zensayyy.fm.proto.Fm.FmControl.class, zensayyy.fm.proto.Fm.FmControl.Builder.class);
      }

      // Construct using zensayyy.fm.proto.Fm.FmControl.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        control_ = 0;
        if (tracksBuilder_ == null) {
          tracks_ = java.util.Collections.emptyList();
        } else {
          tracks_ = null;
          tracksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmControl_descriptor;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmControl getDefaultInstanceForType() {
        return zensayyy.fm.proto.Fm.FmControl.getDefaultInstance();
      }

      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmControl build() {
        zensayyy.fm.proto.Fm.FmControl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmControl buildPartial() {
        zensayyy.fm.proto.Fm.FmControl result = new zensayyy.fm.proto.Fm.FmControl(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(zensayyy.fm.proto.Fm.FmControl result) {
        if (tracksBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            tracks_ = java.util.Collections.unmodifiableList(tracks_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.tracks_ = tracks_;
        } else {
          result.tracks_ = tracksBuilder_.build();
        }
      }

      private void buildPartial0(zensayyy.fm.proto.Fm.FmControl result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.control_ = control_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zensayyy.fm.proto.Fm.FmControl) {
          return mergeFrom((zensayyy.fm.proto.Fm.FmControl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zensayyy.fm.proto.Fm.FmControl other) {
        if (other == zensayyy.fm.proto.Fm.FmControl.getDefaultInstance()) return this;
        if (other.control_ != 0) {
          setControlValue(other.getControlValue());
        }
        if (tracksBuilder_ == null) {
          if (!other.tracks_.isEmpty()) {
            if (tracks_.isEmpty()) {
              tracks_ = other.tracks_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTracksIsMutable();
              tracks_.addAll(other.tracks_);
            }
            onChanged();
          }
        } else {
          if (!other.tracks_.isEmpty()) {
            if (tracksBuilder_.isEmpty()) {
              tracksBuilder_.dispose();
              tracksBuilder_ = null;
              tracks_ = other.tracks_;
              bitField0_ = (bitField0_ & ~0x00000002);
              tracksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTracksFieldBuilder() : null;
            } else {
              tracksBuilder_.addAllMessages(other.tracks_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                control_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                zensayyy.fm.proto.TrackOuterClass.Track m =
                    input.readMessage(
                        zensayyy.fm.proto.TrackOuterClass.Track.parser(),
                        extensionRegistry);
                if (tracksBuilder_ == null) {
                  ensureTracksIsMutable();
                  tracks_.add(m);
                } else {
                  tracksBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int control_ = 0;
      /**
       * <code>.zensayyy.fm.proto.FmControl.Control control = 1;</code>
       * @return The enum numeric value on the wire for control.
       */
      @java.lang.Override public int getControlValue() {
        return control_;
      }
      /**
       * <code>.zensayyy.fm.proto.FmControl.Control control = 1;</code>
       * @param value The enum numeric value on the wire for control to set.
       * @return This builder for chaining.
       */
      public Builder setControlValue(int value) {
        control_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.FmControl.Control control = 1;</code>
       * @return The control.
       */
      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmControl.Control getControl() {
        zensayyy.fm.proto.Fm.FmControl.Control result = zensayyy.fm.proto.Fm.FmControl.Control.forNumber(control_);
        return result == null ? zensayyy.fm.proto.Fm.FmControl.Control.UNRECOGNIZED : result;
      }
      /**
       * <code>.zensayyy.fm.proto.FmControl.Control control = 1;</code>
       * @param value The control to set.
       * @return This builder for chaining.
       */
      public Builder setControl(zensayyy.fm.proto.Fm.FmControl.Control value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        control_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.FmControl.Control control = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearControl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        control_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<zensayyy.fm.proto.TrackOuterClass.Track> tracks_ =
        java.util.Collections.emptyList();
      private void ensureTracksIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          tracks_ = new java.util.ArrayList<zensayyy.fm.proto.TrackOuterClass.Track>(tracks_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          zensayyy.fm.proto.TrackOuterClass.Track, zensayyy.fm.proto.TrackOuterClass.Track.Builder, zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder> tracksBuilder_;

      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public java.util.List<zensayyy.fm.proto.TrackOuterClass.Track> getTracksList() {
        if (tracksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tracks_);
        } else {
          return tracksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public int getTracksCount() {
        if (tracksBuilder_ == null) {
          return tracks_.size();
        } else {
          return tracksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public zensayyy.fm.proto.TrackOuterClass.Track getTracks(int index) {
        if (tracksBuilder_ == null) {
          return tracks_.get(index);
        } else {
          return tracksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public Builder setTracks(
          int index, zensayyy.fm.proto.TrackOuterClass.Track value) {
        if (tracksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTracksIsMutable();
          tracks_.set(index, value);
          onChanged();
        } else {
          tracksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public Builder setTracks(
          int index, zensayyy.fm.proto.TrackOuterClass.Track.Builder builderForValue) {
        if (tracksBuilder_ == null) {
          ensureTracksIsMutable();
          tracks_.set(index, builderForValue.build());
          onChanged();
        } else {
          tracksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public Builder addTracks(zensayyy.fm.proto.TrackOuterClass.Track value) {
        if (tracksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTracksIsMutable();
          tracks_.add(value);
          onChanged();
        } else {
          tracksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public Builder addTracks(
          int index, zensayyy.fm.proto.TrackOuterClass.Track value) {
        if (tracksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTracksIsMutable();
          tracks_.add(index, value);
          onChanged();
        } else {
          tracksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public Builder addTracks(
          zensayyy.fm.proto.TrackOuterClass.Track.Builder builderForValue) {
        if (tracksBuilder_ == null) {
          ensureTracksIsMutable();
          tracks_.add(builderForValue.build());
          onChanged();
        } else {
          tracksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public Builder addTracks(
          int index, zensayyy.fm.proto.TrackOuterClass.Track.Builder builderForValue) {
        if (tracksBuilder_ == null) {
          ensureTracksIsMutable();
          tracks_.add(index, builderForValue.build());
          onChanged();
        } else {
          tracksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public Builder addAllTracks(
          java.lang.Iterable<? extends zensayyy.fm.proto.TrackOuterClass.Track> values) {
        if (tracksBuilder_ == null) {
          ensureTracksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tracks_);
          onChanged();
        } else {
          tracksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public Builder clearTracks() {
        if (tracksBuilder_ == null) {
          tracks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          tracksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public Builder removeTracks(int index) {
        if (tracksBuilder_ == null) {
          ensureTracksIsMutable();
          tracks_.remove(index);
          onChanged();
        } else {
          tracksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public zensayyy.fm.proto.TrackOuterClass.Track.Builder getTracksBuilder(
          int index) {
        return getTracksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder getTracksOrBuilder(
          int index) {
        if (tracksBuilder_ == null) {
          return tracks_.get(index);  } else {
          return tracksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public java.util.List<? extends zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder> 
           getTracksOrBuilderList() {
        if (tracksBuilder_ != null) {
          return tracksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tracks_);
        }
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public zensayyy.fm.proto.TrackOuterClass.Track.Builder addTracksBuilder() {
        return getTracksFieldBuilder().addBuilder(
            zensayyy.fm.proto.TrackOuterClass.Track.getDefaultInstance());
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public zensayyy.fm.proto.TrackOuterClass.Track.Builder addTracksBuilder(
          int index) {
        return getTracksFieldBuilder().addBuilder(
            index, zensayyy.fm.proto.TrackOuterClass.Track.getDefaultInstance());
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 2;</code>
       */
      public java.util.List<zensayyy.fm.proto.TrackOuterClass.Track.Builder> 
           getTracksBuilderList() {
        return getTracksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          zensayyy.fm.proto.TrackOuterClass.Track, zensayyy.fm.proto.TrackOuterClass.Track.Builder, zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder> 
          getTracksFieldBuilder() {
        if (tracksBuilder_ == null) {
          tracksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              zensayyy.fm.proto.TrackOuterClass.Track, zensayyy.fm.proto.TrackOuterClass.Track.Builder, zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder>(
                  tracks_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          tracks_ = null;
        }
        return tracksBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zensayyy.fm.proto.FmControl)
    }

    // @@protoc_insertion_point(class_scope:zensayyy.fm.proto.FmControl)
    private static final zensayyy.fm.proto.Fm.FmControl DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zensayyy.fm.proto.Fm.FmControl();
    }

    public static zensayyy.fm.proto.Fm.FmControl getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FmControl>
        PARSER = new com.google.protobuf.AbstractParser<FmControl>() {
      @java.lang.Override
      public FmControl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FmControl> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FmControl> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public zensayyy.fm.proto.Fm.FmControl getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FmJoinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zensayyy.fm.proto.FmJoin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string streamId = 1;</code>
     * @return The streamId.
     */
    java.lang.String getStreamId();
    /**
     * <code>string streamId = 1;</code>
     * @return The bytes for streamId.
     */
    com.google.protobuf.ByteString
        getStreamIdBytes();
  }
  /**
   * <pre>
   *&#47; Join Message send by the clients
   * </pre>
   *
   * Protobuf type {@code zensayyy.fm.proto.FmJoin}
   */
  public static final class FmJoin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zensayyy.fm.proto.FmJoin)
      FmJoinOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FmJoin.newBuilder() to construct.
    private FmJoin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FmJoin() {
      streamId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FmJoin();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmJoin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmJoin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zensayyy.fm.proto.Fm.FmJoin.class, zensayyy.fm.proto.Fm.FmJoin.Builder.class);
    }

    public static final int STREAMID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object streamId_ = "";
    /**
     * <code>string streamId = 1;</code>
     * @return The streamId.
     */
    @java.lang.Override
    public java.lang.String getStreamId() {
      java.lang.Object ref = streamId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streamId_ = s;
        return s;
      }
    }
    /**
     * <code>string streamId = 1;</code>
     * @return The bytes for streamId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreamIdBytes() {
      java.lang.Object ref = streamId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streamId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(streamId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, streamId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(streamId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, streamId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zensayyy.fm.proto.Fm.FmJoin)) {
        return super.equals(obj);
      }
      zensayyy.fm.proto.Fm.FmJoin other = (zensayyy.fm.proto.Fm.FmJoin) obj;

      if (!getStreamId()
          .equals(other.getStreamId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STREAMID_FIELD_NUMBER;
      hash = (53 * hash) + getStreamId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zensayyy.fm.proto.Fm.FmJoin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Fm.FmJoin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmJoin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Fm.FmJoin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmJoin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Fm.FmJoin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmJoin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Fm.FmJoin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmJoin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Fm.FmJoin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmJoin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Fm.FmJoin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zensayyy.fm.proto.Fm.FmJoin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *&#47; Join Message send by the clients
     * </pre>
     *
     * Protobuf type {@code zensayyy.fm.proto.FmJoin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zensayyy.fm.proto.FmJoin)
        zensayyy.fm.proto.Fm.FmJoinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmJoin_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmJoin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zensayyy.fm.proto.Fm.FmJoin.class, zensayyy.fm.proto.Fm.FmJoin.Builder.class);
      }

      // Construct using zensayyy.fm.proto.Fm.FmJoin.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        streamId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmJoin_descriptor;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmJoin getDefaultInstanceForType() {
        return zensayyy.fm.proto.Fm.FmJoin.getDefaultInstance();
      }

      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmJoin build() {
        zensayyy.fm.proto.Fm.FmJoin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmJoin buildPartial() {
        zensayyy.fm.proto.Fm.FmJoin result = new zensayyy.fm.proto.Fm.FmJoin(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(zensayyy.fm.proto.Fm.FmJoin result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.streamId_ = streamId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zensayyy.fm.proto.Fm.FmJoin) {
          return mergeFrom((zensayyy.fm.proto.Fm.FmJoin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zensayyy.fm.proto.Fm.FmJoin other) {
        if (other == zensayyy.fm.proto.Fm.FmJoin.getDefaultInstance()) return this;
        if (!other.getStreamId().isEmpty()) {
          streamId_ = other.streamId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                streamId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object streamId_ = "";
      /**
       * <code>string streamId = 1;</code>
       * @return The streamId.
       */
      public java.lang.String getStreamId() {
        java.lang.Object ref = streamId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          streamId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string streamId = 1;</code>
       * @return The bytes for streamId.
       */
      public com.google.protobuf.ByteString
          getStreamIdBytes() {
        java.lang.Object ref = streamId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streamId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string streamId = 1;</code>
       * @param value The streamId to set.
       * @return This builder for chaining.
       */
      public Builder setStreamId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        streamId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string streamId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreamId() {
        streamId_ = getDefaultInstance().getStreamId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string streamId = 1;</code>
       * @param value The bytes for streamId to set.
       * @return This builder for chaining.
       */
      public Builder setStreamIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        streamId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zensayyy.fm.proto.FmJoin)
    }

    // @@protoc_insertion_point(class_scope:zensayyy.fm.proto.FmJoin)
    private static final zensayyy.fm.proto.Fm.FmJoin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zensayyy.fm.proto.Fm.FmJoin();
    }

    public static zensayyy.fm.proto.Fm.FmJoin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FmJoin>
        PARSER = new com.google.protobuf.AbstractParser<FmJoin>() {
      @java.lang.Override
      public FmJoin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FmJoin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FmJoin> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public zensayyy.fm.proto.Fm.FmJoin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FmProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zensayyy.fm.proto.FmProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp time = 1;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>.google.protobuf.Timestamp time = 1;</code>
     * @return The time.
     */
    com.google.protobuf.Timestamp getTime();
    /**
     * <code>.google.protobuf.Timestamp time = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();

    /**
     * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
     * @return Whether the join field is set.
     */
    boolean hasJoin();
    /**
     * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
     * @return The join.
     */
    zensayyy.fm.proto.Fm.FmJoin getJoin();
    /**
     * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
     */
    zensayyy.fm.proto.Fm.FmJoinOrBuilder getJoinOrBuilder();

    /**
     * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
     * @return Whether the control field is set.
     */
    boolean hasControl();
    /**
     * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
     * @return The control.
     */
    zensayyy.fm.proto.Fm.FmControl getControl();
    /**
     * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
     */
    zensayyy.fm.proto.Fm.FmControlOrBuilder getControlOrBuilder();

    zensayyy.fm.proto.Fm.FmProtocol.MsgCase getMsgCase();
  }
  /**
   * <pre>
   *&#47; FmProtocol Message
   * </pre>
   *
   * Protobuf type {@code zensayyy.fm.proto.FmProtocol}
   */
  public static final class FmProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zensayyy.fm.proto.FmProtocol)
      FmProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FmProtocol.newBuilder() to construct.
    private FmProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FmProtocol() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FmProtocol();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmProtocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zensayyy.fm.proto.Fm.FmProtocol.class, zensayyy.fm.proto.Fm.FmProtocol.Builder.class);
    }

    private int msgCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      JOIN(2),
      CONTROL(3),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 2: return JOIN;
          case 3: return CONTROL;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp time_;
    /**
     * <code>.google.protobuf.Timestamp time = 1;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return time_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTime() {
      return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
      return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
    }

    public static final int JOIN_FIELD_NUMBER = 2;
    /**
     * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
     * @return Whether the join field is set.
     */
    @java.lang.Override
    public boolean hasJoin() {
      return msgCase_ == 2;
    }
    /**
     * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
     * @return The join.
     */
    @java.lang.Override
    public zensayyy.fm.proto.Fm.FmJoin getJoin() {
      if (msgCase_ == 2) {
         return (zensayyy.fm.proto.Fm.FmJoin) msg_;
      }
      return zensayyy.fm.proto.Fm.FmJoin.getDefaultInstance();
    }
    /**
     * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
     */
    @java.lang.Override
    public zensayyy.fm.proto.Fm.FmJoinOrBuilder getJoinOrBuilder() {
      if (msgCase_ == 2) {
         return (zensayyy.fm.proto.Fm.FmJoin) msg_;
      }
      return zensayyy.fm.proto.Fm.FmJoin.getDefaultInstance();
    }

    public static final int CONTROL_FIELD_NUMBER = 3;
    /**
     * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
     * @return Whether the control field is set.
     */
    @java.lang.Override
    public boolean hasControl() {
      return msgCase_ == 3;
    }
    /**
     * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
     * @return The control.
     */
    @java.lang.Override
    public zensayyy.fm.proto.Fm.FmControl getControl() {
      if (msgCase_ == 3) {
         return (zensayyy.fm.proto.Fm.FmControl) msg_;
      }
      return zensayyy.fm.proto.Fm.FmControl.getDefaultInstance();
    }
    /**
     * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
     */
    @java.lang.Override
    public zensayyy.fm.proto.Fm.FmControlOrBuilder getControlOrBuilder() {
      if (msgCase_ == 3) {
         return (zensayyy.fm.proto.Fm.FmControl) msg_;
      }
      return zensayyy.fm.proto.Fm.FmControl.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != null) {
        output.writeMessage(1, getTime());
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (zensayyy.fm.proto.Fm.FmJoin) msg_);
      }
      if (msgCase_ == 3) {
        output.writeMessage(3, (zensayyy.fm.proto.Fm.FmControl) msg_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTime());
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (zensayyy.fm.proto.Fm.FmJoin) msg_);
      }
      if (msgCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (zensayyy.fm.proto.Fm.FmControl) msg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zensayyy.fm.proto.Fm.FmProtocol)) {
        return super.equals(obj);
      }
      zensayyy.fm.proto.Fm.FmProtocol other = (zensayyy.fm.proto.Fm.FmProtocol) obj;

      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (!getTime()
            .equals(other.getTime())) return false;
      }
      if (!getMsgCase().equals(other.getMsgCase())) return false;
      switch (msgCase_) {
        case 2:
          if (!getJoin()
              .equals(other.getJoin())) return false;
          break;
        case 3:
          if (!getControl()
              .equals(other.getControl())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      switch (msgCase_) {
        case 2:
          hash = (37 * hash) + JOIN_FIELD_NUMBER;
          hash = (53 * hash) + getJoin().hashCode();
          break;
        case 3:
          hash = (37 * hash) + CONTROL_FIELD_NUMBER;
          hash = (53 * hash) + getControl().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zensayyy.fm.proto.Fm.FmProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Fm.FmProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Fm.FmProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Fm.FmProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Fm.FmProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Fm.FmProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Fm.FmProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Fm.FmProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zensayyy.fm.proto.Fm.FmProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *&#47; FmProtocol Message
     * </pre>
     *
     * Protobuf type {@code zensayyy.fm.proto.FmProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zensayyy.fm.proto.FmProtocol)
        zensayyy.fm.proto.Fm.FmProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmProtocol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zensayyy.fm.proto.Fm.FmProtocol.class, zensayyy.fm.proto.Fm.FmProtocol.Builder.class);
      }

      // Construct using zensayyy.fm.proto.Fm.FmProtocol.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        time_ = null;
        if (timeBuilder_ != null) {
          timeBuilder_.dispose();
          timeBuilder_ = null;
        }
        if (joinBuilder_ != null) {
          joinBuilder_.clear();
        }
        if (controlBuilder_ != null) {
          controlBuilder_.clear();
        }
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zensayyy.fm.proto.Fm.internal_static_zensayyy_fm_proto_FmProtocol_descriptor;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmProtocol getDefaultInstanceForType() {
        return zensayyy.fm.proto.Fm.FmProtocol.getDefaultInstance();
      }

      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmProtocol build() {
        zensayyy.fm.proto.Fm.FmProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmProtocol buildPartial() {
        zensayyy.fm.proto.Fm.FmProtocol result = new zensayyy.fm.proto.Fm.FmProtocol(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(zensayyy.fm.proto.Fm.FmProtocol result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.time_ = timeBuilder_ == null
              ? time_
              : timeBuilder_.build();
        }
      }

      private void buildPartialOneofs(zensayyy.fm.proto.Fm.FmProtocol result) {
        result.msgCase_ = msgCase_;
        result.msg_ = this.msg_;
        if (msgCase_ == 2 &&
            joinBuilder_ != null) {
          result.msg_ = joinBuilder_.build();
        }
        if (msgCase_ == 3 &&
            controlBuilder_ != null) {
          result.msg_ = controlBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zensayyy.fm.proto.Fm.FmProtocol) {
          return mergeFrom((zensayyy.fm.proto.Fm.FmProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zensayyy.fm.proto.Fm.FmProtocol other) {
        if (other == zensayyy.fm.proto.Fm.FmProtocol.getDefaultInstance()) return this;
        if (other.hasTime()) {
          mergeTime(other.getTime());
        }
        switch (other.getMsgCase()) {
          case JOIN: {
            mergeJoin(other.getJoin());
            break;
          }
          case CONTROL: {
            mergeControl(other.getControl());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getJoinFieldBuilder().getBuilder(),
                    extensionRegistry);
                msgCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getControlFieldBuilder().getBuilder(),
                    extensionRegistry);
                msgCase_ = 3;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.Timestamp time_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       * @return Whether the time field is set.
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       * @return The time.
       */
      public com.google.protobuf.Timestamp getTime() {
        if (timeBuilder_ == null) {
          return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        } else {
          return timeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      public Builder setTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          time_ = value;
        } else {
          timeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      public Builder setTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timeBuilder_ == null) {
          time_ = builderForValue.build();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      public Builder mergeTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            time_ != null &&
            time_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getTimeBuilder().mergeFrom(value);
          } else {
            time_ = value;
          }
        } else {
          timeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = null;
        if (timeBuilder_ != null) {
          timeBuilder_.dispose();
          timeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          return time_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTime(),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          zensayyy.fm.proto.Fm.FmJoin, zensayyy.fm.proto.Fm.FmJoin.Builder, zensayyy.fm.proto.Fm.FmJoinOrBuilder> joinBuilder_;
      /**
       * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
       * @return Whether the join field is set.
       */
      @java.lang.Override
      public boolean hasJoin() {
        return msgCase_ == 2;
      }
      /**
       * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
       * @return The join.
       */
      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmJoin getJoin() {
        if (joinBuilder_ == null) {
          if (msgCase_ == 2) {
            return (zensayyy.fm.proto.Fm.FmJoin) msg_;
          }
          return zensayyy.fm.proto.Fm.FmJoin.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return joinBuilder_.getMessage();
          }
          return zensayyy.fm.proto.Fm.FmJoin.getDefaultInstance();
        }
      }
      /**
       * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
       */
      public Builder setJoin(zensayyy.fm.proto.Fm.FmJoin value) {
        if (joinBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          joinBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
       */
      public Builder setJoin(
          zensayyy.fm.proto.Fm.FmJoin.Builder builderForValue) {
        if (joinBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          joinBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
       */
      public Builder mergeJoin(zensayyy.fm.proto.Fm.FmJoin value) {
        if (joinBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != zensayyy.fm.proto.Fm.FmJoin.getDefaultInstance()) {
            msg_ = zensayyy.fm.proto.Fm.FmJoin.newBuilder((zensayyy.fm.proto.Fm.FmJoin) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            joinBuilder_.mergeFrom(value);
          } else {
            joinBuilder_.setMessage(value);
          }
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
       */
      public Builder clearJoin() {
        if (joinBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          joinBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
       */
      public zensayyy.fm.proto.Fm.FmJoin.Builder getJoinBuilder() {
        return getJoinFieldBuilder().getBuilder();
      }
      /**
       * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
       */
      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmJoinOrBuilder getJoinOrBuilder() {
        if ((msgCase_ == 2) && (joinBuilder_ != null)) {
          return joinBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (zensayyy.fm.proto.Fm.FmJoin) msg_;
          }
          return zensayyy.fm.proto.Fm.FmJoin.getDefaultInstance();
        }
      }
      /**
       * <code>.zensayyy.fm.proto.FmJoin join = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          zensayyy.fm.proto.Fm.FmJoin, zensayyy.fm.proto.Fm.FmJoin.Builder, zensayyy.fm.proto.Fm.FmJoinOrBuilder> 
          getJoinFieldBuilder() {
        if (joinBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = zensayyy.fm.proto.Fm.FmJoin.getDefaultInstance();
          }
          joinBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              zensayyy.fm.proto.Fm.FmJoin, zensayyy.fm.proto.Fm.FmJoin.Builder, zensayyy.fm.proto.Fm.FmJoinOrBuilder>(
                  (zensayyy.fm.proto.Fm.FmJoin) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();
        return joinBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          zensayyy.fm.proto.Fm.FmControl, zensayyy.fm.proto.Fm.FmControl.Builder, zensayyy.fm.proto.Fm.FmControlOrBuilder> controlBuilder_;
      /**
       * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
       * @return Whether the control field is set.
       */
      @java.lang.Override
      public boolean hasControl() {
        return msgCase_ == 3;
      }
      /**
       * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
       * @return The control.
       */
      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmControl getControl() {
        if (controlBuilder_ == null) {
          if (msgCase_ == 3) {
            return (zensayyy.fm.proto.Fm.FmControl) msg_;
          }
          return zensayyy.fm.proto.Fm.FmControl.getDefaultInstance();
        } else {
          if (msgCase_ == 3) {
            return controlBuilder_.getMessage();
          }
          return zensayyy.fm.proto.Fm.FmControl.getDefaultInstance();
        }
      }
      /**
       * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
       */
      public Builder setControl(zensayyy.fm.proto.Fm.FmControl value) {
        if (controlBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          controlBuilder_.setMessage(value);
        }
        msgCase_ = 3;
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
       */
      public Builder setControl(
          zensayyy.fm.proto.Fm.FmControl.Builder builderForValue) {
        if (controlBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          controlBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 3;
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
       */
      public Builder mergeControl(zensayyy.fm.proto.Fm.FmControl value) {
        if (controlBuilder_ == null) {
          if (msgCase_ == 3 &&
              msg_ != zensayyy.fm.proto.Fm.FmControl.getDefaultInstance()) {
            msg_ = zensayyy.fm.proto.Fm.FmControl.newBuilder((zensayyy.fm.proto.Fm.FmControl) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 3) {
            controlBuilder_.mergeFrom(value);
          } else {
            controlBuilder_.setMessage(value);
          }
        }
        msgCase_ = 3;
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
       */
      public Builder clearControl() {
        if (controlBuilder_ == null) {
          if (msgCase_ == 3) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 3) {
            msgCase_ = 0;
            msg_ = null;
          }
          controlBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
       */
      public zensayyy.fm.proto.Fm.FmControl.Builder getControlBuilder() {
        return getControlFieldBuilder().getBuilder();
      }
      /**
       * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
       */
      @java.lang.Override
      public zensayyy.fm.proto.Fm.FmControlOrBuilder getControlOrBuilder() {
        if ((msgCase_ == 3) && (controlBuilder_ != null)) {
          return controlBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 3) {
            return (zensayyy.fm.proto.Fm.FmControl) msg_;
          }
          return zensayyy.fm.proto.Fm.FmControl.getDefaultInstance();
        }
      }
      /**
       * <code>.zensayyy.fm.proto.FmControl control = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          zensayyy.fm.proto.Fm.FmControl, zensayyy.fm.proto.Fm.FmControl.Builder, zensayyy.fm.proto.Fm.FmControlOrBuilder> 
          getControlFieldBuilder() {
        if (controlBuilder_ == null) {
          if (!(msgCase_ == 3)) {
            msg_ = zensayyy.fm.proto.Fm.FmControl.getDefaultInstance();
          }
          controlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              zensayyy.fm.proto.Fm.FmControl, zensayyy.fm.proto.Fm.FmControl.Builder, zensayyy.fm.proto.Fm.FmControlOrBuilder>(
                  (zensayyy.fm.proto.Fm.FmControl) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 3;
        onChanged();
        return controlBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zensayyy.fm.proto.FmProtocol)
    }

    // @@protoc_insertion_point(class_scope:zensayyy.fm.proto.FmProtocol)
    private static final zensayyy.fm.proto.Fm.FmProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zensayyy.fm.proto.Fm.FmProtocol();
    }

    public static zensayyy.fm.proto.Fm.FmProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FmProtocol>
        PARSER = new com.google.protobuf.AbstractParser<FmProtocol>() {
      @java.lang.Override
      public FmProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FmProtocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FmProtocol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public zensayyy.fm.proto.Fm.FmProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zensayyy_fm_proto_FmControl_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zensayyy_fm_proto_FmControl_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zensayyy_fm_proto_FmJoin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zensayyy_fm_proto_FmJoin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zensayyy_fm_proto_FmProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zensayyy_fm_proto_FmProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021protocol/Fm.proto\022\021zensayyy.fm.proto\032\037" +
      "google/protobuf/timestamp.proto\032\024protoco" +
      "l/Track.proto\"\217\001\n\tFmControl\0225\n\007control\030\001" +
      " \001(\0162$.zensayyy.fm.proto.FmControl.Contr" +
      "ol\022(\n\006tracks\030\002 \003(\0132\030.zensayyy.fm.proto.T" +
      "rack\"!\n\007Control\022\014\n\010SYNC_REQ\020\000\022\010\n\004DATA\020\001\"" +
      "\032\n\006FmJoin\022\020\n\010streamId\030\001 \001(\t\"\231\001\n\nFmProtoc" +
      "ol\022(\n\004time\030\001 \001(\0132\032.google.protobuf.Times" +
      "tamp\022)\n\004join\030\002 \001(\0132\031.zensayyy.fm.proto.F" +
      "mJoinH\000\022/\n\007control\030\003 \001(\0132\034.zensayyy.fm.p" +
      "roto.FmControlH\000B\005\n\003msgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          zensayyy.fm.proto.TrackOuterClass.getDescriptor(),
        });
    internal_static_zensayyy_fm_proto_FmControl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zensayyy_fm_proto_FmControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zensayyy_fm_proto_FmControl_descriptor,
        new java.lang.String[] { "Control", "Tracks", });
    internal_static_zensayyy_fm_proto_FmJoin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zensayyy_fm_proto_FmJoin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zensayyy_fm_proto_FmJoin_descriptor,
        new java.lang.String[] { "StreamId", });
    internal_static_zensayyy_fm_proto_FmProtocol_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_zensayyy_fm_proto_FmProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zensayyy_fm_proto_FmProtocol_descriptor,
        new java.lang.String[] { "Time", "Join", "Control", "Msg", });
    com.google.protobuf.TimestampProto.getDescriptor();
    zensayyy.fm.proto.TrackOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
