// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/Mixer.proto

package zensayyy.fm.proto;

public final class Mixer {
  private Mixer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MixerControlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zensayyy.fm.proto.MixerControl)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string steamId = 1;</code>
     * @return The steamId.
     */
    java.lang.String getSteamId();
    /**
     * <code>string steamId = 1;</code>
     * @return The bytes for steamId.
     */
    com.google.protobuf.ByteString
        getSteamIdBytes();

    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>.zensayyy.fm.proto.MixerControl.Control control = 3;</code>
     * @return The enum numeric value on the wire for control.
     */
    int getControlValue();
    /**
     * <code>.zensayyy.fm.proto.MixerControl.Control control = 3;</code>
     * @return The control.
     */
    zensayyy.fm.proto.Mixer.MixerControl.Control getControl();

    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
     */
    java.util.List<zensayyy.fm.proto.TrackOuterClass.Track> 
        getTracksList();
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
     */
    zensayyy.fm.proto.TrackOuterClass.Track getTracks(int index);
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
     */
    int getTracksCount();
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
     */
    java.util.List<? extends zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder> 
        getTracksOrBuilderList();
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
     */
    zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder getTracksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code zensayyy.fm.proto.MixerControl}
   */
  public static final class MixerControl extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zensayyy.fm.proto.MixerControl)
      MixerControlOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MixerControl.newBuilder() to construct.
    private MixerControl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MixerControl() {
      steamId_ = "";
      token_ = "";
      control_ = 0;
      tracks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MixerControl();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zensayyy.fm.proto.Mixer.internal_static_zensayyy_fm_proto_MixerControl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zensayyy.fm.proto.Mixer.internal_static_zensayyy_fm_proto_MixerControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zensayyy.fm.proto.Mixer.MixerControl.class, zensayyy.fm.proto.Mixer.MixerControl.Builder.class);
    }

    /**
     * Protobuf enum {@code zensayyy.fm.proto.MixerControl.Control}
     */
    public enum Control
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DATA = 0;</code>
       */
      DATA(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DATA = 0;</code>
       */
      public static final int DATA_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Control valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Control forNumber(int value) {
        switch (value) {
          case 0: return DATA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Control>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Control> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Control>() {
              public Control findValueByNumber(int number) {
                return Control.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return zensayyy.fm.proto.Mixer.MixerControl.getDescriptor().getEnumTypes().get(0);
      }

      private static final Control[] VALUES = values();

      public static Control valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Control(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:zensayyy.fm.proto.MixerControl.Control)
    }

    public static final int STEAMID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object steamId_ = "";
    /**
     * <code>string steamId = 1;</code>
     * @return The steamId.
     */
    @java.lang.Override
    public java.lang.String getSteamId() {
      java.lang.Object ref = steamId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        steamId_ = s;
        return s;
      }
    }
    /**
     * <code>string steamId = 1;</code>
     * @return The bytes for steamId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSteamIdBytes() {
      java.lang.Object ref = steamId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        steamId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object token_ = "";
    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTROL_FIELD_NUMBER = 3;
    private int control_ = 0;
    /**
     * <code>.zensayyy.fm.proto.MixerControl.Control control = 3;</code>
     * @return The enum numeric value on the wire for control.
     */
    @java.lang.Override public int getControlValue() {
      return control_;
    }
    /**
     * <code>.zensayyy.fm.proto.MixerControl.Control control = 3;</code>
     * @return The control.
     */
    @java.lang.Override public zensayyy.fm.proto.Mixer.MixerControl.Control getControl() {
      zensayyy.fm.proto.Mixer.MixerControl.Control result = zensayyy.fm.proto.Mixer.MixerControl.Control.forNumber(control_);
      return result == null ? zensayyy.fm.proto.Mixer.MixerControl.Control.UNRECOGNIZED : result;
    }

    public static final int TRACKS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<zensayyy.fm.proto.TrackOuterClass.Track> tracks_;
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
     */
    @java.lang.Override
    public java.util.List<zensayyy.fm.proto.TrackOuterClass.Track> getTracksList() {
      return tracks_;
    }
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder> 
        getTracksOrBuilderList() {
      return tracks_;
    }
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
     */
    @java.lang.Override
    public int getTracksCount() {
      return tracks_.size();
    }
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
     */
    @java.lang.Override
    public zensayyy.fm.proto.TrackOuterClass.Track getTracks(int index) {
      return tracks_.get(index);
    }
    /**
     * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
     */
    @java.lang.Override
    public zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder getTracksOrBuilder(
        int index) {
      return tracks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(steamId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, steamId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      if (control_ != zensayyy.fm.proto.Mixer.MixerControl.Control.DATA.getNumber()) {
        output.writeEnum(3, control_);
      }
      for (int i = 0; i < tracks_.size(); i++) {
        output.writeMessage(4, tracks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(steamId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, steamId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      if (control_ != zensayyy.fm.proto.Mixer.MixerControl.Control.DATA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, control_);
      }
      for (int i = 0; i < tracks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, tracks_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zensayyy.fm.proto.Mixer.MixerControl)) {
        return super.equals(obj);
      }
      zensayyy.fm.proto.Mixer.MixerControl other = (zensayyy.fm.proto.Mixer.MixerControl) obj;

      if (!getSteamId()
          .equals(other.getSteamId())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (control_ != other.control_) return false;
      if (!getTracksList()
          .equals(other.getTracksList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STEAMID_FIELD_NUMBER;
      hash = (53 * hash) + getSteamId().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + CONTROL_FIELD_NUMBER;
      hash = (53 * hash) + control_;
      if (getTracksCount() > 0) {
        hash = (37 * hash) + TRACKS_FIELD_NUMBER;
        hash = (53 * hash) + getTracksList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zensayyy.fm.proto.Mixer.MixerControl parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Mixer.MixerControl parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Mixer.MixerControl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Mixer.MixerControl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Mixer.MixerControl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Mixer.MixerControl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Mixer.MixerControl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Mixer.MixerControl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Mixer.MixerControl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Mixer.MixerControl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Mixer.MixerControl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Mixer.MixerControl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zensayyy.fm.proto.Mixer.MixerControl prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zensayyy.fm.proto.MixerControl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zensayyy.fm.proto.MixerControl)
        zensayyy.fm.proto.Mixer.MixerControlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zensayyy.fm.proto.Mixer.internal_static_zensayyy_fm_proto_MixerControl_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zensayyy.fm.proto.Mixer.internal_static_zensayyy_fm_proto_MixerControl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zensayyy.fm.proto.Mixer.MixerControl.class, zensayyy.fm.proto.Mixer.MixerControl.Builder.class);
      }

      // Construct using zensayyy.fm.proto.Mixer.MixerControl.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        steamId_ = "";
        token_ = "";
        control_ = 0;
        if (tracksBuilder_ == null) {
          tracks_ = java.util.Collections.emptyList();
        } else {
          tracks_ = null;
          tracksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zensayyy.fm.proto.Mixer.internal_static_zensayyy_fm_proto_MixerControl_descriptor;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Mixer.MixerControl getDefaultInstanceForType() {
        return zensayyy.fm.proto.Mixer.MixerControl.getDefaultInstance();
      }

      @java.lang.Override
      public zensayyy.fm.proto.Mixer.MixerControl build() {
        zensayyy.fm.proto.Mixer.MixerControl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Mixer.MixerControl buildPartial() {
        zensayyy.fm.proto.Mixer.MixerControl result = new zensayyy.fm.proto.Mixer.MixerControl(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(zensayyy.fm.proto.Mixer.MixerControl result) {
        if (tracksBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            tracks_ = java.util.Collections.unmodifiableList(tracks_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.tracks_ = tracks_;
        } else {
          result.tracks_ = tracksBuilder_.build();
        }
      }

      private void buildPartial0(zensayyy.fm.proto.Mixer.MixerControl result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.steamId_ = steamId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.token_ = token_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.control_ = control_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zensayyy.fm.proto.Mixer.MixerControl) {
          return mergeFrom((zensayyy.fm.proto.Mixer.MixerControl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zensayyy.fm.proto.Mixer.MixerControl other) {
        if (other == zensayyy.fm.proto.Mixer.MixerControl.getDefaultInstance()) return this;
        if (!other.getSteamId().isEmpty()) {
          steamId_ = other.steamId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.control_ != 0) {
          setControlValue(other.getControlValue());
        }
        if (tracksBuilder_ == null) {
          if (!other.tracks_.isEmpty()) {
            if (tracks_.isEmpty()) {
              tracks_ = other.tracks_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureTracksIsMutable();
              tracks_.addAll(other.tracks_);
            }
            onChanged();
          }
        } else {
          if (!other.tracks_.isEmpty()) {
            if (tracksBuilder_.isEmpty()) {
              tracksBuilder_.dispose();
              tracksBuilder_ = null;
              tracks_ = other.tracks_;
              bitField0_ = (bitField0_ & ~0x00000008);
              tracksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTracksFieldBuilder() : null;
            } else {
              tracksBuilder_.addAllMessages(other.tracks_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                steamId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                token_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                control_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                zensayyy.fm.proto.TrackOuterClass.Track m =
                    input.readMessage(
                        zensayyy.fm.proto.TrackOuterClass.Track.parser(),
                        extensionRegistry);
                if (tracksBuilder_ == null) {
                  ensureTracksIsMutable();
                  tracks_.add(m);
                } else {
                  tracksBuilder_.addMessage(m);
                }
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object steamId_ = "";
      /**
       * <code>string steamId = 1;</code>
       * @return The steamId.
       */
      public java.lang.String getSteamId() {
        java.lang.Object ref = steamId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          steamId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string steamId = 1;</code>
       * @return The bytes for steamId.
       */
      public com.google.protobuf.ByteString
          getSteamIdBytes() {
        java.lang.Object ref = steamId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          steamId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string steamId = 1;</code>
       * @param value The steamId to set.
       * @return This builder for chaining.
       */
      public Builder setSteamId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        steamId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string steamId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSteamId() {
        steamId_ = getDefaultInstance().getSteamId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string steamId = 1;</code>
       * @param value The bytes for steamId to set.
       * @return This builder for chaining.
       */
      public Builder setSteamIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        steamId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 2;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        token_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        token_ = getDefaultInstance().getToken();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        token_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int control_ = 0;
      /**
       * <code>.zensayyy.fm.proto.MixerControl.Control control = 3;</code>
       * @return The enum numeric value on the wire for control.
       */
      @java.lang.Override public int getControlValue() {
        return control_;
      }
      /**
       * <code>.zensayyy.fm.proto.MixerControl.Control control = 3;</code>
       * @param value The enum numeric value on the wire for control to set.
       * @return This builder for chaining.
       */
      public Builder setControlValue(int value) {
        control_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.MixerControl.Control control = 3;</code>
       * @return The control.
       */
      @java.lang.Override
      public zensayyy.fm.proto.Mixer.MixerControl.Control getControl() {
        zensayyy.fm.proto.Mixer.MixerControl.Control result = zensayyy.fm.proto.Mixer.MixerControl.Control.forNumber(control_);
        return result == null ? zensayyy.fm.proto.Mixer.MixerControl.Control.UNRECOGNIZED : result;
      }
      /**
       * <code>.zensayyy.fm.proto.MixerControl.Control control = 3;</code>
       * @param value The control to set.
       * @return This builder for chaining.
       */
      public Builder setControl(zensayyy.fm.proto.Mixer.MixerControl.Control value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        control_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.MixerControl.Control control = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearControl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        control_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<zensayyy.fm.proto.TrackOuterClass.Track> tracks_ =
        java.util.Collections.emptyList();
      private void ensureTracksIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          tracks_ = new java.util.ArrayList<zensayyy.fm.proto.TrackOuterClass.Track>(tracks_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          zensayyy.fm.proto.TrackOuterClass.Track, zensayyy.fm.proto.TrackOuterClass.Track.Builder, zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder> tracksBuilder_;

      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public java.util.List<zensayyy.fm.proto.TrackOuterClass.Track> getTracksList() {
        if (tracksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tracks_);
        } else {
          return tracksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public int getTracksCount() {
        if (tracksBuilder_ == null) {
          return tracks_.size();
        } else {
          return tracksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public zensayyy.fm.proto.TrackOuterClass.Track getTracks(int index) {
        if (tracksBuilder_ == null) {
          return tracks_.get(index);
        } else {
          return tracksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public Builder setTracks(
          int index, zensayyy.fm.proto.TrackOuterClass.Track value) {
        if (tracksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTracksIsMutable();
          tracks_.set(index, value);
          onChanged();
        } else {
          tracksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public Builder setTracks(
          int index, zensayyy.fm.proto.TrackOuterClass.Track.Builder builderForValue) {
        if (tracksBuilder_ == null) {
          ensureTracksIsMutable();
          tracks_.set(index, builderForValue.build());
          onChanged();
        } else {
          tracksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public Builder addTracks(zensayyy.fm.proto.TrackOuterClass.Track value) {
        if (tracksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTracksIsMutable();
          tracks_.add(value);
          onChanged();
        } else {
          tracksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public Builder addTracks(
          int index, zensayyy.fm.proto.TrackOuterClass.Track value) {
        if (tracksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTracksIsMutable();
          tracks_.add(index, value);
          onChanged();
        } else {
          tracksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public Builder addTracks(
          zensayyy.fm.proto.TrackOuterClass.Track.Builder builderForValue) {
        if (tracksBuilder_ == null) {
          ensureTracksIsMutable();
          tracks_.add(builderForValue.build());
          onChanged();
        } else {
          tracksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public Builder addTracks(
          int index, zensayyy.fm.proto.TrackOuterClass.Track.Builder builderForValue) {
        if (tracksBuilder_ == null) {
          ensureTracksIsMutable();
          tracks_.add(index, builderForValue.build());
          onChanged();
        } else {
          tracksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public Builder addAllTracks(
          java.lang.Iterable<? extends zensayyy.fm.proto.TrackOuterClass.Track> values) {
        if (tracksBuilder_ == null) {
          ensureTracksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tracks_);
          onChanged();
        } else {
          tracksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public Builder clearTracks() {
        if (tracksBuilder_ == null) {
          tracks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          tracksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public Builder removeTracks(int index) {
        if (tracksBuilder_ == null) {
          ensureTracksIsMutable();
          tracks_.remove(index);
          onChanged();
        } else {
          tracksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public zensayyy.fm.proto.TrackOuterClass.Track.Builder getTracksBuilder(
          int index) {
        return getTracksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder getTracksOrBuilder(
          int index) {
        if (tracksBuilder_ == null) {
          return tracks_.get(index);  } else {
          return tracksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public java.util.List<? extends zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder> 
           getTracksOrBuilderList() {
        if (tracksBuilder_ != null) {
          return tracksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tracks_);
        }
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public zensayyy.fm.proto.TrackOuterClass.Track.Builder addTracksBuilder() {
        return getTracksFieldBuilder().addBuilder(
            zensayyy.fm.proto.TrackOuterClass.Track.getDefaultInstance());
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public zensayyy.fm.proto.TrackOuterClass.Track.Builder addTracksBuilder(
          int index) {
        return getTracksFieldBuilder().addBuilder(
            index, zensayyy.fm.proto.TrackOuterClass.Track.getDefaultInstance());
      }
      /**
       * <code>repeated .zensayyy.fm.proto.Track tracks = 4;</code>
       */
      public java.util.List<zensayyy.fm.proto.TrackOuterClass.Track.Builder> 
           getTracksBuilderList() {
        return getTracksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          zensayyy.fm.proto.TrackOuterClass.Track, zensayyy.fm.proto.TrackOuterClass.Track.Builder, zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder> 
          getTracksFieldBuilder() {
        if (tracksBuilder_ == null) {
          tracksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              zensayyy.fm.proto.TrackOuterClass.Track, zensayyy.fm.proto.TrackOuterClass.Track.Builder, zensayyy.fm.proto.TrackOuterClass.TrackOrBuilder>(
                  tracks_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          tracks_ = null;
        }
        return tracksBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zensayyy.fm.proto.MixerControl)
    }

    // @@protoc_insertion_point(class_scope:zensayyy.fm.proto.MixerControl)
    private static final zensayyy.fm.proto.Mixer.MixerControl DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zensayyy.fm.proto.Mixer.MixerControl();
    }

    public static zensayyy.fm.proto.Mixer.MixerControl getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MixerControl>
        PARSER = new com.google.protobuf.AbstractParser<MixerControl>() {
      @java.lang.Override
      public MixerControl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MixerControl> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MixerControl> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public zensayyy.fm.proto.Mixer.MixerControl getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MixerProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zensayyy.fm.proto.MixerProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp time = 1;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>.google.protobuf.Timestamp time = 1;</code>
     * @return The time.
     */
    com.google.protobuf.Timestamp getTime();
    /**
     * <code>.google.protobuf.Timestamp time = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();

    /**
     * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
     * @return Whether the control field is set.
     */
    boolean hasControl();
    /**
     * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
     * @return The control.
     */
    zensayyy.fm.proto.Mixer.MixerControl getControl();
    /**
     * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
     */
    zensayyy.fm.proto.Mixer.MixerControlOrBuilder getControlOrBuilder();

    zensayyy.fm.proto.Mixer.MixerProtocol.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code zensayyy.fm.proto.MixerProtocol}
   */
  public static final class MixerProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zensayyy.fm.proto.MixerProtocol)
      MixerProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MixerProtocol.newBuilder() to construct.
    private MixerProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MixerProtocol() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MixerProtocol();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zensayyy.fm.proto.Mixer.internal_static_zensayyy_fm_proto_MixerProtocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zensayyy.fm.proto.Mixer.internal_static_zensayyy_fm_proto_MixerProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zensayyy.fm.proto.Mixer.MixerProtocol.class, zensayyy.fm.proto.Mixer.MixerProtocol.Builder.class);
    }

    private int msgCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      CONTROL(2),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 2: return CONTROL;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp time_;
    /**
     * <code>.google.protobuf.Timestamp time = 1;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return time_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTime() {
      return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
      return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
    }

    public static final int CONTROL_FIELD_NUMBER = 2;
    /**
     * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
     * @return Whether the control field is set.
     */
    @java.lang.Override
    public boolean hasControl() {
      return msgCase_ == 2;
    }
    /**
     * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
     * @return The control.
     */
    @java.lang.Override
    public zensayyy.fm.proto.Mixer.MixerControl getControl() {
      if (msgCase_ == 2) {
         return (zensayyy.fm.proto.Mixer.MixerControl) msg_;
      }
      return zensayyy.fm.proto.Mixer.MixerControl.getDefaultInstance();
    }
    /**
     * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
     */
    @java.lang.Override
    public zensayyy.fm.proto.Mixer.MixerControlOrBuilder getControlOrBuilder() {
      if (msgCase_ == 2) {
         return (zensayyy.fm.proto.Mixer.MixerControl) msg_;
      }
      return zensayyy.fm.proto.Mixer.MixerControl.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != null) {
        output.writeMessage(1, getTime());
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (zensayyy.fm.proto.Mixer.MixerControl) msg_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTime());
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (zensayyy.fm.proto.Mixer.MixerControl) msg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zensayyy.fm.proto.Mixer.MixerProtocol)) {
        return super.equals(obj);
      }
      zensayyy.fm.proto.Mixer.MixerProtocol other = (zensayyy.fm.proto.Mixer.MixerProtocol) obj;

      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (!getTime()
            .equals(other.getTime())) return false;
      }
      if (!getMsgCase().equals(other.getMsgCase())) return false;
      switch (msgCase_) {
        case 2:
          if (!getControl()
              .equals(other.getControl())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      switch (msgCase_) {
        case 2:
          hash = (37 * hash) + CONTROL_FIELD_NUMBER;
          hash = (53 * hash) + getControl().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zensayyy.fm.proto.Mixer.MixerProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Mixer.MixerProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Mixer.MixerProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Mixer.MixerProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Mixer.MixerProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zensayyy.fm.proto.Mixer.MixerProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zensayyy.fm.proto.Mixer.MixerProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Mixer.MixerProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Mixer.MixerProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Mixer.MixerProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zensayyy.fm.proto.Mixer.MixerProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zensayyy.fm.proto.Mixer.MixerProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zensayyy.fm.proto.Mixer.MixerProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zensayyy.fm.proto.MixerProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zensayyy.fm.proto.MixerProtocol)
        zensayyy.fm.proto.Mixer.MixerProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zensayyy.fm.proto.Mixer.internal_static_zensayyy_fm_proto_MixerProtocol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zensayyy.fm.proto.Mixer.internal_static_zensayyy_fm_proto_MixerProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zensayyy.fm.proto.Mixer.MixerProtocol.class, zensayyy.fm.proto.Mixer.MixerProtocol.Builder.class);
      }

      // Construct using zensayyy.fm.proto.Mixer.MixerProtocol.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        time_ = null;
        if (timeBuilder_ != null) {
          timeBuilder_.dispose();
          timeBuilder_ = null;
        }
        if (controlBuilder_ != null) {
          controlBuilder_.clear();
        }
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zensayyy.fm.proto.Mixer.internal_static_zensayyy_fm_proto_MixerProtocol_descriptor;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Mixer.MixerProtocol getDefaultInstanceForType() {
        return zensayyy.fm.proto.Mixer.MixerProtocol.getDefaultInstance();
      }

      @java.lang.Override
      public zensayyy.fm.proto.Mixer.MixerProtocol build() {
        zensayyy.fm.proto.Mixer.MixerProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public zensayyy.fm.proto.Mixer.MixerProtocol buildPartial() {
        zensayyy.fm.proto.Mixer.MixerProtocol result = new zensayyy.fm.proto.Mixer.MixerProtocol(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(zensayyy.fm.proto.Mixer.MixerProtocol result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.time_ = timeBuilder_ == null
              ? time_
              : timeBuilder_.build();
        }
      }

      private void buildPartialOneofs(zensayyy.fm.proto.Mixer.MixerProtocol result) {
        result.msgCase_ = msgCase_;
        result.msg_ = this.msg_;
        if (msgCase_ == 2 &&
            controlBuilder_ != null) {
          result.msg_ = controlBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zensayyy.fm.proto.Mixer.MixerProtocol) {
          return mergeFrom((zensayyy.fm.proto.Mixer.MixerProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zensayyy.fm.proto.Mixer.MixerProtocol other) {
        if (other == zensayyy.fm.proto.Mixer.MixerProtocol.getDefaultInstance()) return this;
        if (other.hasTime()) {
          mergeTime(other.getTime());
        }
        switch (other.getMsgCase()) {
          case CONTROL: {
            mergeControl(other.getControl());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getControlFieldBuilder().getBuilder(),
                    extensionRegistry);
                msgCase_ = 2;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.Timestamp time_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       * @return Whether the time field is set.
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       * @return The time.
       */
      public com.google.protobuf.Timestamp getTime() {
        if (timeBuilder_ == null) {
          return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        } else {
          return timeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      public Builder setTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          time_ = value;
        } else {
          timeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      public Builder setTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timeBuilder_ == null) {
          time_ = builderForValue.build();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      public Builder mergeTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            time_ != null &&
            time_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getTimeBuilder().mergeFrom(value);
          } else {
            time_ = value;
          }
        } else {
          timeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = null;
        if (timeBuilder_ != null) {
          timeBuilder_.dispose();
          timeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          return time_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp time = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTime(),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          zensayyy.fm.proto.Mixer.MixerControl, zensayyy.fm.proto.Mixer.MixerControl.Builder, zensayyy.fm.proto.Mixer.MixerControlOrBuilder> controlBuilder_;
      /**
       * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
       * @return Whether the control field is set.
       */
      @java.lang.Override
      public boolean hasControl() {
        return msgCase_ == 2;
      }
      /**
       * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
       * @return The control.
       */
      @java.lang.Override
      public zensayyy.fm.proto.Mixer.MixerControl getControl() {
        if (controlBuilder_ == null) {
          if (msgCase_ == 2) {
            return (zensayyy.fm.proto.Mixer.MixerControl) msg_;
          }
          return zensayyy.fm.proto.Mixer.MixerControl.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return controlBuilder_.getMessage();
          }
          return zensayyy.fm.proto.Mixer.MixerControl.getDefaultInstance();
        }
      }
      /**
       * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
       */
      public Builder setControl(zensayyy.fm.proto.Mixer.MixerControl value) {
        if (controlBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          controlBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
       */
      public Builder setControl(
          zensayyy.fm.proto.Mixer.MixerControl.Builder builderForValue) {
        if (controlBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          controlBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
       */
      public Builder mergeControl(zensayyy.fm.proto.Mixer.MixerControl value) {
        if (controlBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != zensayyy.fm.proto.Mixer.MixerControl.getDefaultInstance()) {
            msg_ = zensayyy.fm.proto.Mixer.MixerControl.newBuilder((zensayyy.fm.proto.Mixer.MixerControl) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            controlBuilder_.mergeFrom(value);
          } else {
            controlBuilder_.setMessage(value);
          }
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
       */
      public Builder clearControl() {
        if (controlBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          controlBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
       */
      public zensayyy.fm.proto.Mixer.MixerControl.Builder getControlBuilder() {
        return getControlFieldBuilder().getBuilder();
      }
      /**
       * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
       */
      @java.lang.Override
      public zensayyy.fm.proto.Mixer.MixerControlOrBuilder getControlOrBuilder() {
        if ((msgCase_ == 2) && (controlBuilder_ != null)) {
          return controlBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (zensayyy.fm.proto.Mixer.MixerControl) msg_;
          }
          return zensayyy.fm.proto.Mixer.MixerControl.getDefaultInstance();
        }
      }
      /**
       * <code>.zensayyy.fm.proto.MixerControl control = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          zensayyy.fm.proto.Mixer.MixerControl, zensayyy.fm.proto.Mixer.MixerControl.Builder, zensayyy.fm.proto.Mixer.MixerControlOrBuilder> 
          getControlFieldBuilder() {
        if (controlBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = zensayyy.fm.proto.Mixer.MixerControl.getDefaultInstance();
          }
          controlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              zensayyy.fm.proto.Mixer.MixerControl, zensayyy.fm.proto.Mixer.MixerControl.Builder, zensayyy.fm.proto.Mixer.MixerControlOrBuilder>(
                  (zensayyy.fm.proto.Mixer.MixerControl) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();
        return controlBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zensayyy.fm.proto.MixerProtocol)
    }

    // @@protoc_insertion_point(class_scope:zensayyy.fm.proto.MixerProtocol)
    private static final zensayyy.fm.proto.Mixer.MixerProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zensayyy.fm.proto.Mixer.MixerProtocol();
    }

    public static zensayyy.fm.proto.Mixer.MixerProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MixerProtocol>
        PARSER = new com.google.protobuf.AbstractParser<MixerProtocol>() {
      @java.lang.Override
      public MixerProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MixerProtocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MixerProtocol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public zensayyy.fm.proto.Mixer.MixerProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zensayyy_fm_proto_MixerControl_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zensayyy_fm_proto_MixerControl_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zensayyy_fm_proto_MixerProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zensayyy_fm_proto_MixerProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protocol/Mixer.proto\022\021zensayyy.fm.prot" +
      "o\032\024protocol/Track.proto\032\037google/protobuf" +
      "/timestamp.proto\"\247\001\n\014MixerControl\022\017\n\007ste" +
      "amId\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\0228\n\007control\030\003 \001" +
      "(\0162\'.zensayyy.fm.proto.MixerControl.Cont" +
      "rol\022(\n\006tracks\030\004 \003(\0132\030.zensayyy.fm.proto." +
      "Track\"\023\n\007Control\022\010\n\004DATA\020\000\"t\n\rMixerProto" +
      "col\022(\n\004time\030\001 \001(\0132\032.google.protobuf.Time" +
      "stamp\0222\n\007control\030\002 \001(\0132\037.zensayyy.fm.pro" +
      "to.MixerControlH\000B\005\n\003msgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          zensayyy.fm.proto.TrackOuterClass.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_zensayyy_fm_proto_MixerControl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zensayyy_fm_proto_MixerControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zensayyy_fm_proto_MixerControl_descriptor,
        new java.lang.String[] { "SteamId", "Token", "Control", "Tracks", });
    internal_static_zensayyy_fm_proto_MixerProtocol_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zensayyy_fm_proto_MixerProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zensayyy_fm_proto_MixerProtocol_descriptor,
        new java.lang.String[] { "Time", "Control", "Msg", });
    zensayyy.fm.proto.TrackOuterClass.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
